name = "http_gun_comparison"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_time = "== 1.11.0"
http_gun = { path = "../http_gun" }
dream_http_client = { path = "../dream-bbc4b5402a7e0cb5247829c8f4be8fb273afc2a5/modules/http_client" }
gleam_stdlib = "== 0.71.0"
gleam_erlang = "== 1.3.0"
gleam_http = "== 4.4.0"
gleam_json = "== 3.1.0"
gleam_yielder = "== 1.1.0"
simplifile = "== 2.7.0"
