#let terms = (
  (slug: "term-client-view", title: [Client view], body: [An immutable HTTP client handle carrying per-call settings over the same pool. Copies share pool lifetime while their view settings remain independent.]),
  (slug: "term-origin", title: [Origin], body: [The canonical tuple of lowercase unbracketed host, effective port and TLS choice. It identifies a connection lane within one client's immutable connection policy.]),
  (slug: "term-exchange", title: [Exchange], body: [One request attempt with its observed response or failure. It has local identity and supplies no remote idempotency guarantee.]),
  (slug: "term-stream-lease", title: [Stream lease], body: [One exchange's claim on transport capacity. It occupies one exclusive HTTP/1.1 connection or one HTTP/2 stream.]),
  (slug: "term-body-capability", title: [Body capability], body: [A process-owned reference to one response cursor and terminal outcome. Copies refer to the same read and close authority.]),
  (slug: "term-open-body-slot", title: [Open body slot], body: [A retained-body admission slot occupied until the body closes or its process exits. HTTP termination can release a stream lease without releasing this slot.]),
  (slug: "term-submission-evidence", title: [Submission evidence], body: [The distinction between an attempt known to precede the transport request call and one that may have reached the peer. Neither alternative proves remote execution.]),
  (slug: "term-checked-answer", title: [Checked answer], body: [The complete address set admitted for one new connection. Its authority lasts for that connection rather than for the hostname indefinitely.]),
  (slug: "term-view-destination", title: [View destination], body: [A per-call policy that selects hosts or refuses an address class admitted by the client. A plaintext-only restriction does not select a destination.]),
  (slug: "term-flow-credit", title: [Flow credit], body: [Permission for Gun to deliver a response data event. It counts messages rather than bytes or parser allocations.]),
  (slug: "term-read-wait", title: [Read wait], body: [One pending demand for the next body event. Its optional local expiry ends that wait without ending the exchange.]),
  (slug: "term-playback-session", title: [Playback session], body: [An offline client's ordered consumption cursor over a validated script. A mismatch does not advance that cursor.]),
  (slug: "term-capture-reservation", title: [Capture reservation], body: [An exchange position reserved before live execution for a recording. Positions establish fixture order independently of completion order.]),
  (slug: "term-recording-session", title: [Recording session], body: [An owner of bounded captured exchanges and the authority to finalize their fixture. Its result is independent of the live HTTP result.]),
  (slug: "term-cassette", title: [Cassette], body: [A versioned JSON value containing ordered HTTP request and reply observations. It is data rather than a live network or playback capability.]),
  (slug: "term-publication", title: [Publication], body: [The atomic filesystem operation making a complete cassette visible at its destination. Visibility does not establish persistence through power loss.]),
  (slug: "term-request-id", title: [Request id], body: [An opaque identity for one observed invocation within one VM lifetime. It is distinct from the caller's correlation and from a durable remote request identifier.]),
  (slug: "term-http-termination", title: [HTTP termination], body: [The response owner's terminal HTTP observation: completion, local cancellation, deadline expiry or failure. It does not certify application consumption or capture publication.]),
  (slug: "term-redaction", title: [Redaction], body: [The selected removal or rewriting of data retained in fixtures and failure headers. It preserves the live request and does not detect all secrets.]),
)
